//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public int FeedBack_ID { get; set; }
        public string FeedBack_Content { get; set; }
        public int User_ID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
